### ISSUE TITLE
Flow Problems

### ISSUE THREAD

**Issue by EHLSQ** [LecturePulse/web#5]
I'll be adding a list of flow errors that aren't obvious in this issue. 

* AccountView.js, should this.props.children be a generic ReactNode? Should it always expect children?

* ~~Event handler bindings. I'm used to binding through just an arrow function but the support for the syntax doesn't seem to be there. Any info on this error? `file: 'file:///Users/evanli/Desktop/web/src/dashboard/AccountView.js'
severity: 'Error'
message: 'property _changePassword (Covariant property _changePassword incompatible with contravariant use in assignment of property _changePassword)'
at: '74,14'`. This reoccurs for every event handler.~~

* ~~In AccountView, the buttons props being passed in give flow errors. Flow is expecting string? Not sure~~

* ~~In general, we should be passing in props and state for each react component as a type argument. See https://flow.org/en/docs/react/components/.~~

* ~~Flow in vscode is saying that the scss modules are not being found. Some extensions are .css, but the modules are still not found when changing to .scss extension.~~ 

* LectureRecordingGraph, for...in should iterate over object properties

**Comment by reesjones** [comment]
Setting this as a Release Eng milestone since we need a clean repo for our future CI to deploy (flow or lint errors will prevent deployment)
